apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: order
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - order.keptnorder-production.34.76.37.47.xip.io
  - order
  http:
  - route:
    - destination:
        host: order-canary.keptnorder-production.svc.cluster.local
    - destination:
        host: order-primary.keptnorder-production.svc.cluster.local
      weight: 100
