apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: catalog
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - catalog.keptnorder-staging.34.76.37.47.xip.io
  - catalog
  http:
  - route:
    - destination:
        host: catalog.keptnorder-staging.svc.cluster.local
